version: "3.7"
x-logging: &default-logging
    options:
        max-size: "100m"
        max-file: "15"
    driver: json-file

services:
    hiring-db:
        image: mariadb:10.5
        container_name: hiring-db
        restart: unless-stopped
        volumes:
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
            - ./db-data:/var/lib/mysql
        ports:
            - "3307:3306"
        environment:
            MARIADB_ROOT_PASSWORD: 123
        networks:
            hiring-private-net:
                aliases:
                    - local.hiring-db

    hiring-redis:
        container_name: hiring-redis
        image: redis:5.0
        expose:
            - 6379
        volumes:
            - redis-data:/data

    hiring-api:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: hiring-api
        command: [ "sh", "-c", "php -S 0.0.0.0:8000 -t ./public" ]
        tty: true
        user: root
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        ports:
            - "8001:8000"
        deploy:
            resources:
                limits:
                    memory: 3250M
                reservations:
                    memory: 500M
        logging: *default-logging
        networks:
            hiring-private-net:
                aliases:
                    - local.hiring-api
        depends_on:
            - hiring-db
            - hiring-redis

volumes:
  redis-data:

networks:
    hiring-private-net:
